### ISSUE TITLE
Broken Link in the README

### ISSUE THREAD

**Issue by CursedRock17** [iRobotEducation/irobot_create_msgs#16]
#### Steps to reproduce issue

```
Click on the link to have ROS interfaces explained, found at this line in the README: 

https://github.com/iRobotEducation/irobot_create_msgs/blob/rolling/README.md?plain=1#L5
```

#### Expected behavior
Have said interfaces explained
#### Actual behavior
The user gets taken to 404 link on ROS Index

#### Additional information

Odds are this was supposed to link back to the docs, something as easy as:
- https://docs.ros.org/en/rolling/How-To-Guides/Topics-Services-Actions.html

would probably do the trick, but if the user needs more information they could use the starting tutorials, starting here:
- https://docs.ros.org/en/rolling/Tutorials/Beginner-CLI-Tools/Understanding-ROS2-Topics/Understanding-ROS2-Topics.html

**Comment by shamlian** [comment]
Thanks for the report. This link used to be active. Checking the [Wayback Machine](https://web.archive.org/web/20230915000000*/https://index.ros.org/doc/ros2/Concepts/About-ROS-Interfaces/) shows it last archived about a year ago. Searching for some the text from this archived link, I see that the page seems to have moved to https://docs.ros.org/en/rolling/Concepts/Basic/About-Interfaces.html, but that page also no longer appears to be available, having last been archived in [Dec. 2023](https://web.archive.org/web/20230401000000*/https://docs.ros.org/en/rolling/Concepts/Basic/About-Interfaces.html). Interestingly, this link is linked to from [one of the links you suggested](https://docs.ros.org/en/rolling/How-To-Guides/Topics-Services-Actions.html). I am going to check with the ROS 2 devs about whether or not this page removal was intentional.

**Comment by shamlian** [comment]
https://docs.ros.org/en/rolling/Concepts/Basic/About-Interfaces.html is up now; I will update the README to point to this URL.
